# Generated by Django 2.1.4 on 2019-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='작가')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('publish_year', models.CharField(max_length=100, verbose_name='출판 연도')),
                ('number', models.IntegerField(verbose_name='도서 번호')),
                ('location', models.CharField(max_length=250, verbose_name='도서 위치')),
                ('serial_number', models.CharField(max_length=200, verbose_name='도서 고유번호')),
                ('status', models.CharField(max_length=250, verbose_name='도서 상태')),
                ('return_date', models.CharField(max_length=200, verbose_name='반납일')),
            ],
        ),
    ]
