FROM            python:3.6.7-slim
MAINTAINER      dreamong91@gmail.com
ENV             LANG    C.UTF-8


RUN             apt -y update
RUN             apt -y dist-upgrade
RUN             apt -y install gcc nginx supervisor && \
                pip3 install uwsgi && \
                apt -y remove gcc && \
                apt -y autoremove


COPY            requirements-production.txt /tmp/requirements.txt
WORKDIR         /tmp/
RUN             pip3 install -r requirements.txt
