# Generated by Django 2.1.4 on 2019-02-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_profile',
        ),
        migrations.AddField(
            model_name='user',
            name='visited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
